### ISSUE TITLE
Failing installing dependencies

### ISSUE THREAD

**Issue by ramses3** [lightninglabs/lndclient#153]
github.com/lightninglabs/lndclient imports
	github.com/btcsuite/btcd/btcec: cannot find module providing package github.com/btcsuite/btcd/btcec

How can this be solved?

**Comment by guggero** [comment]
You need to use a tagged version of `lndclient`, see https://github.com/lightninglabs/lndclient/tags. Just using `@latest` won't work as that will pull in a very old version.

**Comment by aruokhai** [comment]
One other way to reinstall all dependencie in a project that uses lndclient, delete the sum files and reference to lndclient in the mod file
