### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ardevd** [lightninglabs/lndclient#166]
Is there any official documentation for `lndclient` apart from the one on [pkg.go.dev](https://pkg.go.dev/github.com/lightninglabs/lndclient)? 

Are we still encouraged to use `GrpcLndServices` as opposed to `LightningClient` or `BasicClient`?

**Comment by guggero** [comment]
No, there is no additional documentation as the project is just a wrapper and mostly being used in our own projects. The [`NewLndServices()`](https://pkg.go.dev/github.com/lightninglabs/lndclient#NewLndServices) method offers the most features and should be used if it contains all the RPC methods you need.
The `BasicClient` is just a wrapper around the raw RPC connection and can be used for methods that haven't (yet) been implemented in `lndclient`.

**Comment by ardevd** [comment]
Thanks! After playing around with it for a bit I got the hang of it. Thanks!
