### ISSUE TITLE
Not possible to force closing inactive channel without specifying custom fee?

### ISSUE THREAD

**Issue by ardevd** [lightninglabs/lndclient#168]
I'm trying to implement channel closure functionality with ´lndclient` and I'm facing an issue when trying to force close an inactive channel.

The API requires a `confTarget int32` argument, but attempting to force close a channel leads to an RPC error due to the fact that a custom fee was set.

```golang
lndService.Client.CloseChannel(m.ctx, outPoint, true, 5, address)
```
results in:

`rpc error: code = Unknown desc = force closing a channel uses a pre-defined fee`

Is there a way to not pass a pre-defined fee that I haven't found yet or does `lndclient` need to be updated in order to support closing inactive channels?

**Comment by guggero** [comment]
Force closing a channel means publishing the latest pre-signed channel state. So you cannot override the fee rate as that would require your peer to re-sign the transaction. So not related to `lndclient` at all. If you pass in `true` for force close, you also need to pass in `0` as fees.

**Comment by ardevd** [comment]
Yep, that makes sense. I just figured it would make more sense for the fee argument to be simply ignored if force closure was indicated.

Furthermore, the following attempt seems mark the channel as force closing, but the transaction isn't actually broadcasted onchain. Am I missing something?

```golang
closeUpdates, closeErrors, err := m.lndService.Client.CloseChannel(m.ctx, outPoint, true, 0, nil)
```

**Comment by guggero** [comment]
Yeah, fee too low for your mempool. Need to increase `-maxmempool` of your `bitcoind` node.
