### ISSUE TITLE
No support for Main RPC message signing?

### ISSUE THREAD

**Issue by ardevd** [lightninglabs/lndclient#170]
It seems `lndclient` only implements [this](https://api.lightning.community/api/lnd/signer/sign-message) RPC call for message signing and not the [main RPC implementation](https://api.lightning.community/api/lnd/lightning/sign-message). Am I correct?

This doesn't seem to work for message signing (for Amboss authentication for example). I presume Im using the wrong key.

```
keyLocator := &keychain.KeyLocator{
		Family: keychain.KeyFamilyNodeKey,
	}

	// Call the SignMessage function
	signature, err := m.lndService.Signer.SignMessage(m.ctx, []byte(messageToSign),
		*keyLocator, lndclient.SignCompact())
```

**Comment by guggero** [comment]
Correct. We only added the methods we need in our projects (Loop, Pool, Faraday, Taproot Assets). Feel free to add new methods as PRs if you need them.
I think the main difference between the two signing methods is the format returned, as explained by their documentation.

**Comment by ardevd** [comment]
Appreciate the insight. Any idea why the above code snippet doesn't produce the expected signature? I presumed using keychain.KeyFamilyNodeKey and an index of 0 would give me the private node signing key, similar to what the main RPC message signing call uses?

**Comment by ardevd** [comment]
Added support for the main RPC message signing API. Tested and gives me valid signatures. #171
