### ISSUE TITLE
Missing SubscribeInvoices in LightningClient

### ISSUE THREAD

**Issue by sbres** [lightninglabs/lndclient#24]
Hello,

I'm trying to Subscribe to Lnd incoming invoices
After bootstrapping some code using lnrpc.LightningClient & NewBasicClient, I switched to GrpcLndServices and I found out SubscribeInvoices is not in LightningClient.

Are we not meant to use the LightningClient for that or is it just missing?

**Comment by guggero** [comment]
We encourage everyone to switch over to the more advanced `GrpcLndServices`. But we currently only add features to that as we need them in our projects, therefore it does not contain all RPCs yet. This does not mean you shouldn't use it!

If you feel like adding it yourself, we'd be happy to review your PR!

**Comment by sbres** [comment]
I will definitely give it a try can I use lnrpc.InvoiceSubscription as a parameter for the method or should I make a new struct. Both ways seem to be used.

**Comment by guggero** [comment]
The idea is to wrap the RPC types in native go types and to make the methods more easy to use. The raw RPC types are only used as struct input parameters if there are too many input arguments. For the case of the `SubscribeInvoices`, the two parameters `addIndex` and `settleIndex` can be used directly. And the return value can be a channel of `*Invoice`.
