### ISSUE TITLE
Connecting to LND by supplying raw certs and macaroons

### ISSUE THREAD

**Issue by torkelrogstad** [lightninglabs/lndclient#29]
## Feature request
Add ability to supply raw certs and macaroons as `[]byte`, instead of specifying a path. 

## Motivation
When working with nodes and services running in containers, we do not necessarily have (easy) access to the underlying file system used by a container. Instead, it is easier to read specific files (certs and macaroons) out of the container. Being able to supply these would simplify my work flow.

**Comment by jalavosus** [comment]
#35

**Comment by guggero** [comment]
Implemented by https://github.com/lightninglabs/lndclient/pull/51.
