### ISSUE TITLE
Value rounded to sat in AddInvoice

### ISSUE THREAD

**Issue by sbres** [lightninglabs/lndclient#63]
In the call AddInvoice, the parameter Value that is in mSat is rounded to a full sat in order to be sent in the Value field of the Invoice.
https://github.com/lightninglabs/lndclient/blob/157df0838abcd9fc2212aeadc6948bd9f05fa956/lightning_client.go#L1191
This creates a silent error because if you try to create an invoice of less than a Sat, an invoice for 0 sat is created. This creating an invoice that does not reflect what was requested.

I see that the Invoice structure has the field `ValueMsat`, I think this would be a better fit, the loss of precision will be avoided and the parameters will match the invoice.

**Comment by guggero** [comment]
Fixed by https://github.com/lightninglabs/lndclient/pull/64.
