### ISSUE TITLE
Add signet support

### ISSUE THREAD

**Issue by rsafier** [lightninglabs/lndclient#94]
Would like to connect with a custom signet

**Comment by rsafier** [comment]
I had hacked this in a personal copy but not being a golang person my branch is too messy to merge, but looked like this was all that was really required: https://github.com/rsafier/lndclient/commit/fc95bdfb96495908069db235dc418a6d3e2cf5c1

**Comment by guggero** [comment]
Was added in https://github.com/lightninglabs/lndclient/pull/150 and can be used by any version equal to or greater than `v0.16.0-12`.
